version: '3.11'

services:
  app:
    build: .
    container_name: chatbot-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
    working_dir: /code

  redis:
    image: redis:alpine
    container_name: chatbot-fastapi-redis
